
<div class="row">
  <div class="grid6">
    <h3>Somos la única red publicitaria a nivel nacional para anunciar los productos y servicios de tu empresa</h3>
    <ul>
      <li>Anuncia en los sitios web más importantes del país.</li>
      <li>Elige los días, los portales web y las secciones donde quieres que se vea tu aviso.</li>
    </ul>
    <div class="slideshow"><span class="arrow-left"></span>
      <ul class="slide">
        <li><a href="javascript:;" title="title" class="elcomerciope2"></a></li>
        <li><a href="javascript:;" title="title" class="rppnoticias2"></a></li>
        <li><a href="javascript:;" title="title" class="perucom2"></a></li>
        <li><a href="javascript:;" title="title" class="peru212"></a></li>
        <li><a href="javascript:;" title="title" class="trome2"></a></li>
      </ul><span class="arrow-right"></span>
    </div>
    <div class="registrate">Regístrate hoy y llévate <span class="free">GRATIS </span>un plan de hasta <span class="offer-price">S/.150</span></div><a href="javascript:;" title="¡Arma tu campa&ntilde;a ya!" class="btn campana">¡Arma tu campa&ntilde;a ya!</a>
  </div>
  <div class="grid6">
    <div class="video-presentacion"></div>
  </div>
</div>
<div class="opciones row">
  <div class="col3">
    <div class="panel-home"><span class="fig1"></span>
      <div class="desc">Elige entre 2 tipos de avisos.</div>
    </div>
  </div>
  <div class="col3">
    <div class="panel-home"><span class="fig2"></span>
      <div class="desc">Tus avisos aparecerán de acuerdo al contenido de los portales.</div>
    </div>
  </div>
  <div class="col3">
    <div class="panel-home"><span class="fig3"></span>
      <div class="desc">Puedes monitorear tu campaña y realizar ajustes en cualquier momento.</div>
    </div>
  </div>
  <div class="col3 cend">
    <div class="panel-home"><span class="fig4"></span>
      <div class="desc">Puedes pagar fácilmente con tarjeta de crédito o en efectivo.</div>
    </div>
  </div>
</div>
<h2>Pasos para usar PERURED</h2>
<div class="pasos-de-uso row">
  <div class="video-pasos"></div>
  <ul>
    <li><span class="step">1</span><span class="step-text">Reg&iacute;strate</span><span id="step-registrate" class="step-icon"></span></li>
    <li><span class="step">2</span><span class="step-text">Dise&ntilde;a tu aviso</span><span id="step-disena" class="step-icon"></span></li>
    <li><span class="step">3</span><span class="step-text">Planifica tu pauta</span><span id="step-planifica" class="step-icon"></span></li>
    <li><span class="step">4</span><span class="step-text">Monitorea tu campa&ntilde;a</span><span id="step-monitorea" class="step-icon"></span></li>
  </ul>
</div>
<h2>Red de portales que trabajan con nosotros</h2>
<div class="row">
  <ul class="red-home">
    <li><a href="http://elcomercio.pe" title="ElComercio.pe" target="_blank" class="elcomerciope">ElComercio.pe</a></li>
    <li><a href="http://www.rpp.com.pe" title="Rpp Noticias" target="_blank" class="rppnoticias">Rpp Noticias</a></li>
    <li><a href="http://www.peru.com" title="Peru.com" target="_blank" class="perucom">Peru.com</a></li>
    <li><a href="http://www.peru21.pe" title="Peru21" target="_blank" class="peru21">Peru21</a></li>
    <li><a href="http://www.trome.pe" title="Trome.pe" target="_blank" class="trome">Trome.pe</a></li>
    <li><a href="http://www.depor.pe" title="Depor.pe" target="_blank" class="depor">Depor.pe</a></li>
    <li><a href="http://diariocorreo.pe/" title="Diario Correo" target="_blank" class="correo">Diario Correo</a></li>
    <li><a href="http://www.studio92.com/" title="Studio 92" target="_blank" class="studio92">Studio 92</a></li>
    <li><a href="http://www.gestion.pe" title="Diario Gesti&oacute;n" target="_blank" class="gestion">Diario Gesti&oacute;n</a></li>
    <li><a href="http://www.ojo.pe" title="Diario Ojo" target="_blank" class="ojo">Diario Ojo</a></li>
    <li><a href="http://www.elbocon.pe" title="Diario El Bocon" target="_blank" class="elbocon">Diario El Bocon</a></li>
    <li><a href="http://www.oxigeno.com.pe/" title="Radio Oxigeno" target="_blank" class="oxigeno">Radio Oxigeno</a></li>
    <li><a href="http://aja.pe" title="Diario Aja" target="_blank" class="aja">Diario Aja</a></li>
    <li><a href="http://publimetro.pe/" title="Publimetro" target="_blank" class="publimetro">Publimetro</a></li>
    <li><a href="http://www.capital.com.pe/" title="Radio Capital" target="_blank" class="capital">Radio Capital</a></li>
    <li><a href="http://www.felicidad.com.pe/" title="Radio Felicidad" target="_blank" class="felicidad">Radio Felicidad</a></li>
    <li><a href="http://www.bravaza.pe/" title="Radio Bravaza" target="_blank" class="bravaza">Radio Bravaza</a></li>
    <li><a href="http://lazona.com.pe/" title="Radio La Zona" target="_blank" class="lazona">Radio La Zona</a></li>
  </ul>
</div>