
<div class="row">
<div class="col4">
  <div class="panel-port"><span class="comercio"></span>
    <div class="desc">Versión on-line del diario más importante del país. Cuenta con información actualizada las 24 horas y con el mayor número de usuarios únicos del Perú.</div>
  </div>
</div>
<div class="col4">
  <div class="panel-port"><span class="rpp"></span>
    <div class="desc">Portal de noticias con la mejor y más actualizada información del acontecer nacional e internacional, con toda la experiencia de la radio informativa más grande del Perú.</div>
  </div>
</div>
<div class="col4">
  <div class="panel-port"><span class="perucom"></span>
    <div class="desc">El portal peruano con noticias, fútbol peruano, espectáculos, videos, deportes, política, fútbol, turismo, entretenimiento salud y actualidad.</div>
  </div>
</div>
</div>
<div class="row">
<div class="col4">
  <div class="panel-port"><span class="peru21"></span>
    <div class="desc">Portal de noticias de actualidad política y económica. Incluye información y datos de interés separada por secciones además de fotos, videos y otros.</div>
  </div>
</div>
<div class="col4">
  <div class="panel-port"><span class="trome"></span>
    <div class="desc">Versión on-line del diario Trome con las últimas noticias sobre espectáculos, policiales, deportes, familia y actualidad.</div>
  </div>
</div>
<div class="col4">
  <div class="panel-port"><span class="depor"></span>
    <div class="desc">Portal digital del diario Depor con todas las noticias de deportes, tanto nacionales como internacionales</div>
  </div>
</div>
</div>
<div class="row">
<div class="col4">
  <div class="panel-port"><span class="correo"></span>
    <div class="desc">Portal de noticias de actualidad, política, economía, deportes y espectáculos que centraliza y actualiza minuto a minuto las 17 ediciones locales del diario Correo. Cuenta con producciones audiovisuales de creación propia sin descuidar el acontecer internacional.</div>
  </div>
</div>
<div class="col4">
  <div class="panel-port"><span class="studio92"></span>
    <div class="desc">Portal de entretenimiento dirigido a jóvenes de 17 a 25 años con noticias, música y todas las secuencias de los programas de la radio del mismo nombre. Número 1 en tu música.</div>
  </div>
</div>
<div class="col4">
  <div class="panel-port"><span class="getion"></span>
    <div class="desc">Portal de noticias especializado en información de economía y negocios. Además, incluye artículos de política, tecnología y noticias internacionales.</div>
  </div>
</div>
</div>