
<div class="row">
  <div class="col8">
    <h2>Promociones</h2>
    <p>Encuentra aquí todas las promociones que te ogrece PeruRed.</p>
  </div>
  <div class="sidebar col4">
    <h3>Ejemplos de Anuncio</h3>
    <div class="anuncio">
      <h4>Imagen + Texto</h4>
      <div class="demo-anuncio"><span class="title">Con PeruRed estas a un click de tus clientes</span><img alt="descripcionImagen" src="rutaImagen" width="100" height="100"/>
        <p>PeruRed es la red publicitatia a nivel nacional donde podras anunciar de manera facil los productos y servicios de tu empresa.</p><a href="javascript:;" title="www.perured.pe">www.perured.pe</a>
      </div><a href="javascript:;" title="title">Ver las caracter&iacute;sticas</a>
    </div>
  </div>
</div>