
<div class="row">
  <div class="promociones col8">
    <h2>Promociones</h2>
    <p>Encuentra aquí todas las promociones que te ogrece PeruRed.</p>
    <h3>Registrate hoy y llevate GRATIS un plan de hasta S/.177.</h3>
  </div>
  <div class="sidebar col4">
    <h3>Ejemplos de Anuncio</h3>
    <div class="anuncio">
      <h4>Imagen + Texto</h4>
      <div class="demo-anuncio"><span class="title">Con PeruRed estas a un click de tus clientes</span><span class="logo-small"></span>
        <p>PeruRed es la red publicitatia a nivel nacional donde podras anunciar de manera facil los productos y servicios de tu empresa.</p><a href="javascript:;" title="www.perured.pe">www.perured.pe</a>
      </div><a href="javascript:;" title="title">Ver las caracter&iacute;sticas</a>
    </div>
    <div class="anuncio">
      <h4>Solo Texto</h4>
      <div class="demo-anuncio"><span class="title">Con PeruRed estas a un click de tus clientes</span>
        <p class="soloTexto">PeruRed es la red publicitatia a nivel nacional donde podras anunciar de manera facil los productos y servicios de tu empresa.</p><a href="javascript:;" title="www.perured.pe">www.perured.pe</a>
      </div><a href="javascript:;" title="title">Ver las caracter&iacute;sticas</a>
    </div>
    <div class="conoce">Conoce como se verá tu anuncio en nuestros portales</div>
    <div class="banner"><img width="306" height="128" src="../../../../../img/banner-sidebar.png" alt="descripcionImagen"/></div>
  </div>
</div>