
<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="es"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="es"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="es"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="es"><!--<![endif]-->
<head>
  <meta charset="utf-8"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
  <title>Lema: (10 categorías más populares) | nombreTienda</title>
  <meta name="title" content="Lema: (10 categorías más populares) | nombreTienda"/>
  <meta name="description" content="Pseudo descripcion de la pagina: (nombrar las 5 secciones o categorias más populares). nombreTienda"/>
  <meta name="keywords" content="opcion 1, (10 productos más populares), opcion 2, opcion 3, opcion 4, opcion 5"/>
  <meta name="author" content="Perured.pe"/>
  <meta name="viewport" content="width=device-width"/>
  <meta name="language" content="es"/>
  <meta name="robots" content="index,follow"/>
  <meta name="geo.region" content="PE-LIM"/>
  <meta name="geo.placename" content="Cercado de Lima"/>
  <meta name="geo.position" content="-12.0478;-77.0622"/>
  <meta name="ICBM" content="-12.0478, -77.0622"/>
  <meta property="og:title" content="Lema: (10 categorías más populares) | nombreTienda"/>
  <meta property="og:description" content="Pseudo descripcion de la pagina: (nombrar las 5 secciones o categorias más populares). nombreTienda"/>
  <meta property="og:image" content="img/logo.jpg"/>
  <link href="img/logo.jpg" rel="image_src" type="image/jpeg"/>
  <link href="favicon.ico" rel="icon" type="image/vnd.microsoft.icon"/>
  <link href="favicon.ico" rel="shortcut icon" type="image/x-icon"/>
  <meta name="DC.Title" content="Lema: (10 categorías más populares) | nombreTienda"/>
  <meta name="DC.Creator" content="Perured.pe"/>
  <meta name="DC.Description" content="Pseudo descripcion de la pagina: (nombrar las 5 secciones o categorias más populares). nombreTienda"/>
  <meta name="DC.Publisher" content="Perured.pe"/>
  <meta name="DC.Contributor" content="perucomsultores.pe"/>
  <meta name="DC.Language" content="es"/>
  <script src="../js/lib/html5shiv.js?v=8"></script>
  <link type="text/css" rel="stylesheet" href="../css/layout.css?v=8"/>
  <link type="text/css" rel="stylesheet" href="../css/base.css?v=8"/>
  <link type="text/css" rel="stylesheet" href="../css/application/modules/default/default.css?v=8"/><!--[if lt IE 9]>
  <script src="../js/lib/htm l5shiv.js"></script><![endif]-->
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
  <script type="text/javascript">window.jQuery || document.write(unescape('%3Cscript src="../js/jquery.min.js" type="text/javascript"%3E%3C/script%3E'))</script>
</head>
<body>
  <header> 
    <div class="box-center">
      <h1> <a href="http://local.perured.pe/" title="Perured.pe"><img alt="Perured.pe" src="../img/logo.png?v=8" width="156" height="65"/>Perured.pe</a></h1>
      <ul class="account">
        <li><a href="javascript:;" title="Ingresar">Ingresar</a></li>
        <li><a href="javascript:;" title="Registrarse">Registrarse					</a></li>
      </ul>
      <ul id="main-menu">
        <li><a href="javascript:;" title="Inicio">Inicio</a></li>
        <li><a href="javascript:;" title="C&oacute;mo anunciar" class="active">C&oacute;mo anunciar</a></li>
        <li><a href="javascript:;" title="Tarifas y medios de pago">Tarifas y medios de pago</a></li>
        <li><a href="javascript:;" title="Red de portales">Red de portales</a></li>
        <li><a href="javascript:;" title="Promociones">Promociones</a></li>
        <li><a href="javascript:;" title="Mi cuenta">Mi cuenta</a></li>
      </ul>
    </div>
  </header>
  <div id="wrapper">
    <div class="row">
      <div class="grid6">
        <h3>Somos la única red publicitaria a nivel nacional para anunciar los productos y servicios de tu empresa</h3>
        <ul>
          <li>Anuncia en los sitios web más importantes del país.</li>
          <li>Elige los días, los portales web y las secciones donde quieres que se vea tu aviso.</li>
        </ul>
      </div>
      <div class="grid6"><img alt="" src="../img/video.jpg" width="480" height="360"/></div>
    </div>
    <div class="row">
      <Loren>Ipsum</Loren>
    </div>
    <h2>Pasos para usar PERURED</h2>
    <div class="row"><span class="video"></span></div>
    <h2>Red de portales que trabajan con nosotros</h2>
    <div class="row">
      <ul class="red-home">
        <li><a href="javascript:;" title="ElComercio.pe" class="elcomerciope">ElComercio.pe</a></li>
        <li><a href="javascript:;" title="Rpp Noticias" class="rppnoticias">Rpp Noticias</a></li>
        <li><a href="javascript:;" title="Peru.com" class="perucom">Peru.com</a></li>
        <li><a href="javascript:;" title="Peru21" class="peru21">Peru21</a></li>
        <li><a href="javascript:;" title="Trome.pe" class="trome">Trome.pe</a></li>
        <li><a href="javascript:;" title="Depor.pe" class="depor">Depor.pe</a></li>
        <li><a href="javascript:;" title="Diario Correo" class="correo">Diario Correo</a></li>
        <li><a href="javascript:;" title="Studio 92" class="studio92">Studio 92</a></li>
        <li><a href="javascript:;" title="Diario Gesti&oacute;n" class="gestion">Diario Gesti&oacute;n</a></li>
        <li><a href="javascript:;" title="Diario Ojo" class="ojo">Diario Ojo</a></li>
        <li><a href="javascript:;" title="Diario El Bocon" class="elbocon">Diario El Bocon</a></li>
        <li><a href="javascript:;" title="Radio Oxigeno" class="oxigeno">Radio Oxigeno</a></li>
        <li><a href="javascript:;" title="Diario Aja" class="aja">Diario Aja</a></li>
        <li><a href="javascript:;" title="Publimetro" class="publimetro">Publimetro</a></li>
        <li><a href="javascript:;" title="Radio Capital" class="capital">Radio Capital</a></li>
        <li><a href="javascript:;" title="Radio Felicidad" class="felicidad">Radio Felicidad</a></li>
        <li><a href="javascript:;" title="Radio Bravaza" class="bravaza">Radio Bravaza</a></li>
        <li><a href="javascript:;" title="Radio La Zona" class="lazona">Radio La Zona</a></li>
      </ul>
    </div>
  </div>
  <footer>
    <div class="footer-wrap box-center">
      <div class="row">
        <div class="grid4">
          <h3>Más información</h3>
          <ul>
            <li><a href="javascript:;">Como anunciar</a></li>
            <li><a href="javascript:;">Tarifas y medios de pago</a></li>
            <li><a href="javascript:;">Red de portales</a></li>
          </ul>
        </div>
        <div class="grid8">
          <div class="box-help">
            <h3>Central de ayuda</h3>
            <div class="help-content"><span class="img-help"></span>
              <div class="help-description">
                <p>Tienes alguna duda o consulta, estamos para ayudarte</p><a href="javascript:;" class="btn">Click Aquí</a>
              </div>
            </div>
            <ul class="help-question">
              <li><a href="javascript:;">Preguntas Frecuentes</a></li>
              <li><a href="javascript:;">Ayuda en Línea</a></li>
              <li><a href="javascript:;">Contáctanos vía email</a></li>
              <li><a href="javascript:;">Envíenos su sugerencia</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="means-of-payment box-center"><span>Compras 100% seguras con:</span><a href="javascript:;" class="pefectivo"></a><a href="javascript:;" class="visa"></a><a href="javascript:;" class="verif-visa"></a><a href="javascript:;" class="mastercard"></a><a href="javascript:;" class="smastercard"></a></div>
    <div class="copyright">
      <div class="box-center"><span class="logo-small"></span>
        <ul>
          <li>Per&uacute;Red.pe © 2012</li>
          <li><a href="javascript:;" title="T&eacute;rminos y condiciones">T&eacute;rminos y condiciones</a></li>
          <li><a href="javascript:;" title="Pol&iacute;tica de privacidad">Pol&iacute;tica de privacidad</a></li>
          <li><a href="javascript:;" title="title">Pol&iacute;tica de publicación</a></li>
          <li><a href="javascript:;" title="title">Contáctenos</a></li>
          <li class="last">Todo los derechos reservados</li>
        </ul><a href="javascript:;" title="title" class="book-claims">Libro de reclamaciones</a>
      </div>
    </div>
    <div class="box-center"><span class="visit-also">Visite tambi&eacute;n:</span>
      <ul class="visit-also-list">
        <li><a href="http://elcomercio.pe?referer" title="Diario el Comercio" target="_blank">elcomercio.pe</a></li>
        <li><a href="http://peru.com?referer" title="Peru.com" target="_blank">peru.com</a></li>
        <li><a href="http://peru21.pe?referer" title="Diario Perú21" target="_blank">peru21.pe</a></li>
        <li><a href="http://laprensa.com.pe?referer" title="La Prensa" target="_blank">laprensa.com.pe</a></li>
        <li><a href="http://gestion.pe?referer" title="Diario Gestión" target="_blank">gestion.pe</a></li>
        <li><a href="http://depor.pe?referer" title="Depor.pe" target="_blank">depor.pe</a></li>
        <li><a href="http://trome.pe?referer" title="Diario Trome" target="_blank">trome.pe</a></li>
        <li><a href="http://publimetro.pe?referer" title="Publimetro" target="_blank">publimetro.pe</a></li>
        <li><a href="http://gec.pe?referer" title="GEC" target="_blank">gec.pe</a></li>
        <li><a href="http://clasificados.pe/?referer" title="Clasificados" target="_blank">clasificados.pe</a></li>
        <li><a href="http://aptitus.pe?referer" title="Aptitus" target="_blank">aptitus.pe</a></li>
        <li><a href="http://kotear.pe?referer" title="Kotear" target="_blank">kotear.pe</a></li>
        <li><a href="http://urbania.pe?referer" title="Urbania" target="_blank">urbania.pe</a></li>
        <li><a href="http://neoauto.pe?referer" title="Neoauto" target="_blank">neoauto.pe</a></li>
        <li><a href="http://guiagps.pe?referer" title="GuiaGPS" target="_blank">guiagps.pe</a></li>
        <li><a href="http://ofertop.pe?referer" title="Ofertop" target="_blank">ofertop.pe</a></li>
        <li><a href="http://iquiero.com?referer" title="iQuiero" target="_blank">iquiero.com</a></li>
        <li><a href="http://nuestromercado.pe?referer" title="NuestroMercado" target="_blank">nuestromercado.pe</a></li>
        <li><a href="http://pagoefectivo.pe?referer" title="PagoEfectivo" target="_blank">pagoefectivo.pe</a></li>
        <li class="last"><a href="http://clubsuscriptores.pe?referer" title="Club de Suscriptores" target="_blank">clubsuscriptores.pe</a></li>
      </ul>
    </div>
  </footer>
</body>