<!DOCTYPE html>
<html lang="es">
  <head>
    <title Front-End Architecture></title>
    <link type="text/css" rel="stylesheet" href="../css/layout.css?v=52">
    <link type="text/css" rel="stylesheet" href="../css/base.css?v=52">
    <link type="text/css" rel="stylesheet" href="../css/application/modules/default/default.css?v=52">
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    <script type="text/javascript">window.jQuery || document.write(unescape('%3Cscript src="js/jquery.min.js" type="text/javascript"%3E%3C/script%3E'))
</script>
  </head>
  <body>
    <header></header>
    <div id="wrapper">
      <div class="hola">
        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nam cursus. Morbi ut mi. Nullam enim leo, egestas id, condimentum at, laoreet mattis, massa. </p>
      </div>
    </div>
  </body>
</html>
<Sed>eleifend nonummy diam. Praesent mauris ante, elementum et, bibendum at, posuere sit amet, nibh. Duis tincidunt lectus quis dui viverra vestibulum. </Sed>
<Suspendisse>vulputate aliquam dui. Nulla elementum dui ut augue. Aliquam vehicula mi at mauris. Maecenas placerat, nisl at consequat rhoncus, sem nunc </Suspendisse>
<gravida>justo, quis eleifend arcu velit quis lacus. Morbi magna magna, tincidunt a, mattis non, imperdiet vitae, tellus. Sed odio est, auctor ac, </gravida>
<sollicitudin>in, consequat vitae, orci. Fusce id felis. Vivamus sollicitudin metus eget eros.
  <footer>
    <div class="box-center"><span class="visit-also">Visite tambi&eacute;n:</span>
      <ul class="visit-also-list">
        <li><a href="http://elcomercio.pe?referer" title="Diario el Comercio" target="_blank">elcomercio.pe</a>
        </li>
        <li><a href="http://peru.com?referer" title="Peru.com" target="_blank">peru.com</a>
        </li>
        <li><a href="http://peru21.pe?referer" title="Diario Perú21" target="_blank">peru21.pe</a>
        </li>
        <li><a href="http://laprensa.com.pe?referer" title="La Prensa" target="_blank">laprensa.com.pe</a>
        </li>
        <li><a href="http://gestion.pe?referer" title="Diario Gestión" target="_blank">gestion.pe</a>
        </li>
        <li><a href="http://depor.pe?referer" title="Depor.pe" target="_blank">depor.pe</a>
        </li>
        <li><a href="http://trome.pe?referer" title="Diario Trome" target="_blank">trome.pe</a>
        </li>
        <li><a href="http://publimetro.pe?referer" title="Publimetro" target="_blank">publimetro.pe</a>
        </li>
        <li><a href="http://gec.pe?referer" title="GEC" target="_blank">gec.pe</a>
        </li>
        <li><a href="http://clasificados.pe/?referer" title="Clasificados" target="_blank">clasificados.pe</a>
        </li>
        <li><a href="http://aptitus.pe?referer" title="Aptitus" target="_blank">aptitus.pe</a>
        </li>
        <li><a href="http://kotear.pe?referer" title="Kotear" target="_blank">kotear.pe</a>
        </li>
        <li><a href="http://urbania.pe?referer" title="Urbania" target="_blank">urbania.pe</a>
        </li>
        <li><a href="http://neoauto.pe?referer" title="Neoauto" target="_blank">neoauto.pe</a>
        </li>
        <li><a href="http://guiagps.pe?referer" title="GuiaGPS" target="_blank">guiagps.pe</a>
        </li>
        <li><a href="http://ofertop.pe?referer" title="Ofertop" target="_blank">ofertop.pe</a>
        </li>
        <li><a href="http://iquiero.com?referer" title="iQuiero" target="_blank">iquiero.com</a>
        </li>
        <li><a href="http://nuestromercado.pe?referer" title="NuestroMercado" target="_blank">nuestromercado.pe</a>
        </li>
        <li><a href="http://pagoefectivo.pe?referer" title="PagoEfectivo" target="_blank">pagoefectivo.pe</a>
        </li>
        <li><a href="http://clubsuscriptores.pe?referer" title="Club de Suscriptores" target="_blank">clubsuscriptores.pe</a>
        </li>
        <li class="last"><a href="http://perured.pe?referer" title="PeruRed" target="_blank">perured.pe</a>
        </li>
      </ul>
    </div>
  </footer>
</sollicitudin>